#!/usr/bin/env bash
# Build infra/terraform/envs/dev/terraform.tfvars for CI from repo variables +
# the image pin fields in terraform.tfvars.example (updated by image-promote
# and gateway-build).
#
# Never commit the generated terraform.tfvars (gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_DIR="${ROOT}/infra/terraform/envs/dev"
EXAMPLE="${ENV_DIR}/terraform.tfvars.example"
OUT="${ENV_DIR}/terraform.tfvars"

PROJECT_ID="${GCP_PROJECT_ID:?GCP_PROJECT_ID is required}"
REGION="${GCP_REGION:?GCP_REGION is required}"
DEPLOYER_SA="${GCP_DEPLOYER_SA:?GCP_DEPLOYER_SA is required}"
UPLOADS_BUCKET="${UPLOADS_BUCKET_NAME:-${PROJECT_ID}-paperclip-uploads}"
PUBLIC_URL="${PAPERCLIP_PUBLIC_URL:-}"
AUTH_DISABLE="${PAPERCLIP_AUTH_DISABLE_SIGN_UP:-false}"

[[ -f "${EXAMPLE}" ]] || { echo "missing ${EXAMPLE}" >&2; exit 1; }

extract_quoted() {
  local key="$1"
  local line
  line="$(grep -E "^[[:space:]]*${key}[[:space:]]*=" "${EXAMPLE}" | head -1 || true)"
  if [[ -z "${line}" ]]; then
    echo ""
    return 0
  fi
  sed -E 's/^[^=]*=[[:space:]]*"([^"]*)".*/\1/' <<<"${line}"
}

hcl_string_list() {
  if [[ $# -eq 0 ]]; then
    printf '[]'
    return
  fi
  local out="["
  local first=1
  local id
  for id in "$@"; do
    if [[ "${first}" -eq 1 ]]; then
      first=0
    else
      out+=", "
    fi
    out+="\"${id}\""
  done
  out+="]"
  printf '%s' "${out}"
}

secret_exists() {
  local secret_id="$1"
  gcloud secrets describe "${secret_id}" --project="${PROJECT_ID}" >/dev/null 2>&1
}

secret_has_enabled_version() {
  local secret_id="$1"
  local ver
  ver="$(gcloud secrets versions list "${secret_id}" \
    --project="${PROJECT_ID}" \
    --filter='state=ENABLED' \
    --limit=1 \
    --format='value(name)' 2>/dev/null || true)"
  [[ -n "${ver}" ]]
}

SOURCE_REF="$(extract_quoted paperclip_source_ref)"
DIGEST="$(extract_quoted paperclip_image_digest)"
SCHEMA_LAST="$(extract_quoted paperclip_schema_last_migration)"
SCHEMA_COUNT="$(extract_quoted paperclip_schema_migration_count)"
LITELLM_DIGEST="$(extract_quoted litellm_image_digest)"

SOURCE_REF="${SOURCE_REF:-sha-e55d702}"
DIGEST="${DIGEST:-sha256:PENDING_RUN_IMAGE_PROMOTE}"
LITELLM_DIGEST="${LITELLM_DIGEST:-sha256:PENDING_RUN_GATEWAY_BUILD}"

IMPORT_IDS=()
MOUNT_ANTHROPIC="false"
if command -v gcloud >/dev/null 2>&1; then
  for s in litellm-gemini-api-key litellm-anthropic-api-key litellm-master-key; do
    if secret_exists "${s}"; then
      IMPORT_IDS+=("${s}")
    fi
  done
  if secret_has_enabled_version "litellm-anthropic-api-key"; then
    MOUNT_ANTHROPIC="true"
  fi
fi
if [[ ${#IMPORT_IDS[@]} -eq 0 ]]; then
  IMPORT_IDS=("litellm-gemini-api-key")
fi
IMPORT_HCL="$(hcl_string_list "${IMPORT_IDS[@]}")"

cat > "${OUT}" <<EOF
# Generated by scripts/ci-prepare-tfvars.sh — do not commit.
project_id                     = "${PROJECT_ID}"
region                         = "${REGION}"
deployer_service_account_email = "${DEPLOYER_SA}"
uploads_bucket_name            = "${UPLOADS_BUCKET}"

paperclip_source_ref             = "${SOURCE_REF}"
paperclip_image_digest           = "${DIGEST}"
paperclip_schema_last_migration  = "${SCHEMA_LAST}"
paperclip_schema_migration_count = "${SCHEMA_COUNT}"
paperclip_public_url             = "${PUBLIC_URL}"
paperclip_auth_disable_sign_up   = ${AUTH_DISABLE}

litellm_image_digest        = "${LITELLM_DIGEST}"
litellm_import_secret_ids   = ${IMPORT_HCL}
litellm_mount_anthropic     = ${MOUNT_ANTHROPIC}
EOF

echo "Wrote ${OUT}"
echo "  project_id=${PROJECT_ID}"
echo "  region=${REGION}"
echo "  uploads_bucket_name=${UPLOADS_BUCKET}"
echo "  paperclip_image_digest=${DIGEST}"
echo "  paperclip_public_url=${PUBLIC_URL:-"(empty — service/jobs gated off)"}"
echo "  litellm_image_digest=${LITELLM_DIGEST}"
echo "  litellm_import_secret_ids=${IMPORT_HCL}"
echo "  litellm_mount_anthropic=${MOUNT_ANTHROPIC}"
